In [6]:
import pandas as pd

persone = [
   {
        'nome': 'Mario', # chiave: nome, valore: Marco
        'cognome': 'Ricci',
        'eta': 30,
        'citta': 'Milano',
        'codice_fiscale': 'MRI7894DH45O1P',
        'professione': 'Ingegnere'
    },
    {
        "nome": "Rudy",
        "cognome": "Botosso",
        "eta": 54,
        "citta": "Biella",
        "codice fiscale": "BTTRDY71L15A859E",
        "professione": "Informatico"
    },
    {
        "nome": "Marco",
        "cognome": "Secci",
        "eta": 54,
        "citta": "San Donà di Piave",
        "codice fiscale": "SCCMRC71P22H823A",
        "professione": "Disoccupato"
    },
    {
        'nome':'Andrea',
        'cognome':'Romano',
        'eta': 36,
        'citta': 'Ripatransone',
        'codice_fiscale': 'RNINFEINFIEN',
        'professione': 'Studente'
    },
    {
            'nome': 'Saverio', 
            'cognome': 'Carulli',
            'eta': 34,
            'citta': 'Spinazzola',
            'codice_fiscale': 'CRLSVR92H24O1P',
            'professione': 'Disoccupato'
    },
    {
        'nome': 'Giulia', 
        'cognome': 'Pierro',
        'eta': 25,
        'citta': 'Latina',
        'codice_fiscale': 'PRRGLI7894DH45O1P',
        'professione': 'Studente'
    },
    {
        'nome': 'Fabrice',
        'cognome': 'Cheick',
        'eta': 51,
        'citta': 'Ferrara',
        'codice_fiscale': 'CHKFRC75Z20H231G',      
        'professione': 'Pastore'
    },
    {
        'nome': 'Laura',
        'cognome': 'Ricordi',
        'eta': 35,
        'citta': 'Alessandria',
        'codicefiscale':  'chi lo sa?',
        'professione': 'speriamo hr data analyst'
    },
    {
        'nome': 'Luigia',
        'cognome': 'Valente',
        'eta': 32,
        'citta': 'Avellino',
        'codice_fiscale': 'VLNLGU93R64A783K',
        'professione': 'Receptionist'
    },
    {
        'nome': 'Teresa',
        'cognome': 'Balsamo',
        'eta': 25,
        'citta': 'Roma', 
        'codice_fiscale': 'BLSTRS00H48A024P',
        'professione': 'in_cerca'   
    }
]

df = pd.DataFrame(persone)
df

,nome,cognome,eta,citta,codice_fiscale,professione,codice fiscale,codicefiscale
0,Mario,Ricci,30,Milano,MRI7894DH45O1P,Ingegnere,NaN,NaN
1,Rudy,Botosso,54,Biella,NaN,Informatico,BTTRDY71L15A859E,NaN
2,Marco,Secci,54,San Donà di Piave,NaN,Disoccupato,SCCMRC71P22H823A,NaN
3,Andrea,Romano,36,Ripatransone,RNINFEINFIEN,Studente,NaN,NaN
4,Saverio,Carulli,34,Spinazzola,CRLSVR92H24O1P,Disoccupato,NaN,NaN
5,Giulia,Pierro,25,Latina,PRRGLI7894DH45O1P,Studente,NaN,NaN
6,Fabrice,Cheick,51,Ferrara,CHKFRC75Z20H231G,Pastore,NaN,NaN
7,Laura,Ricordi,35,Alessandria,NaN,speriamo hr data analyst,NaN,chi lo sa?
8,Luigia,Valente,32,Avellino,VLNLGU93R64A783K,Receptionist,NaN,NaN
9,Teresa,Balsamo,25,Roma,BLSTRS00H48A024P,in_cerca,NaN,NaN

In [23]:
studenti = {
    "nome": ["Mario", "Rudy", "Marco", "Andrea", "Saverio",  "Giulia", "Fabrice", "Laura", "Luigia", "Teresa"],
    "cognome": ["Ricci", "Botosso", "Secci", "Romano","Carulli", "Pierro", "Cheick", "Ricordi", "Valente", "Balsamo"],
    "eta" : [30, 54, 54, 36, 34, 25, 51, 35, 32, 25],
    "citta" : ["Milano", "Biella", "San Don di Piave", "Ripatransone", "Spinazzola", "Latina", "Ferrara", "Alessandria", "Avellino", "Roma"],
    "voto": [8, 9, 7, 6, 9, 10, 8, 9, 7, 7]
}

#chiama pandas e crea un dataframe dal dictionary studenti
df = pd.DataFrame(studenti)
df #stampa il dataframe tipo tabella divero  da print dove lo mette in formato csv

      nome  cognome  eta             citta  voto
0    Mario    Ricci   30            Milano     8
1     Rudy  Botosso   54            Biella     9
2    Marco    Secci   54  San Don di Piave     7
3   Andrea   Romano   36      Ripatransone     6
4  Saverio  Carulli   34        Spinazzola     9
5   Giulia   Pierro   25            Latina    10
6  Fabrice   Cheick   51           Ferrara     8
7    Laura  Ricordi   35       Alessandria     9
8   Luigia  Valente   32          Avellino     7
9   Teresa  Balsamo   25              Roma     7

### Stampa la prima riga della tabella

In [13]:
df.head(5)

      nome  cognome  eta             citta  voto
0    Mario    Ricci   30            Milano     8
1     Rudy  Botosso   54            Biella     9
2    Marco    Secci   54  San Don di Piave     7
3   Andrea   Romano   36      Ripatransone     6
4  Saverio  Carulli   34        Spinazzola     9

<h4>  La funzione <Strong>info()</Strong> restituisce informazione del <i>dataframe<i> <h4>

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     10 non-null     str
 1   cognome  10 non-null     str
 2   eta      10 non-null     int64
 3   citta    10 non-null     str
 4   voto     10 non-null     int64
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

- Describe() <strong>restituisce le statistiche descrittive del <i>DataFrame</i> </strong>

|Definizione| Valore |
|-----------|--------|
|count	    | Conta  |   
|mean	    | Media  |
|min	    | Minimo |
|max	    | Massimo|

In [14]:
df.describe()

             eta       voto
count  10.000000  10.000000
mean   37.600000   8.000000
std    11.286176   1.247219
min    25.000000   6.000000
25%    30.500000   7.000000
50%    34.500000   8.000000
75%    47.250000   9.000000
max    54.000000  10.000000

- Restituisce  lista dei nomi

In [21]:
df["nome"]

0      Mario
1       Rudy
2      Marco
3     Andrea
4    Saverio
5     Giulia
6    Fabrice
7      Laura
8     Luigia
9     Teresa
Name: nome, dtype: str

In [24]:
df[["nome", "voto"]]

      nome  voto
0    Mario     8
1     Rudy     9
2    Marco     7
3   Andrea     6
4  Saverio     9
5   Giulia    10
6  Fabrice     8
7    Laura     9
8   Luigia     7
9   Teresa     7